<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Friday 13th of June 2014 08:51:21 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://ipetd1.ipe.kit.edu/adei/includes/hybridauth-2.1.2/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "dj0yJmk9SnpNRHZsa1YyRmJWJmQ9WVdrOWFVMVZhamxHTlRBbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02MQ--", "secret" => "efd3d268e515b324f085a095ee5d694d39433aeb" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "725831678756-7de3svhemi14vpn1fluthj4aqdc1o09b.apps.googleusercontent.com", "secret" => "AeS5QUApu5QhduskYqPOoVtt"),
				"scope" => "https://www.googleapis.com/auth/userinfo.profile " 
			),

			"Facebook" => array ( //safari bug. reinstall Rapport
				"enabled" => true,
				"keys"    => array ( "id" => "1462252387352256", "secret" => "22133dc1d682480257132015b974d50e" ),
				"scope"   => "user_about_me",
				//"display" => "touch"
				"display" => "popup"
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "6bE6Eu8tYuWuEshS1qnH9rVBO", "secret" => "Ga6pcNyD2UM6utuxJ1vvpmXEkBmNnNEKMA2haW80mvQK5Jvr8s" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "753g42poqijzvf", "secret" => "cJpu7ZTfiPfrQQWs" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
